cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$lw/dp9gqKvB83YDqmV2CBeLMeVa4Sr0QkoqNu3.zjsdvvMVaUsVo2
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$I.JwK3fxDZ4U2.y/BPg7AO4.R..hdXEgmpq19S0c1Idm9tWAAJafu
preauthorized:
  emails:
  - melsby@gmail.com
